### PR TITLE
Add meeting participation info

### PR DESCRIPTION
**Pull request by dcmiddle**
Signed-off-by: Dan Middleton <dan.middleton@intel.com>

### CODE REVIEW

**Review by thomas-fossati — APPROVED** [review]
thanks!

**Review by lkatalin — APPROVED** [review]

**Review by KeithMoyer — APPROVED** [review]
Thanks for adding this!

**Comment by thomas-fossati** [comment]
Just a thought: we could also add a pointer to the meeting recordings.

**Comment by dcmiddle** [comment]
> Just a thought: we could also add a pointer to the meeting recordings.

Good idea. Added.

**Review by thomas-fossati — APPROVED** [review]
thanks!

**Pull request merged**
