### PR TITLE
materials: Add the TDISP/SPDM slides

### PR DESCRIPTION
**Pull request by sameo**
From the 2023-06-20 meeting.

### CODE REVIEW

**Comment by gkostal** [comment]
_I'd do it myself I knew how to modify this PR._  @sameo -- can you also add another row to the readme.md file that links to the slide deck?

https://github.com/CCC-Attestation/meetings/blob/main/README.md?plain=1

**Review by shnwc — COMMENTED** [review]
Please update the README.md to list this new presentation.

**Comment by sameo** [comment]
> **Update** @sameo , I created a PR against your fork with the change to readme.md: [sameo#1](https://github.com/sameo/ccc-attestation-meetings/pull/1)

Merged, thanks! This PR should be ready now, sorry for missing the README changes.

**Comment by sameo** [comment]
> Please update the README.md to list this new presentation.

This is done now.

**Review by thomas-fossati — APPROVED** [review]
awesome, thanks!

**Review by gkostal — APPROVED** [review]
Thanks Samuel!

**Pull request merged**
