### PR TITLE
Adding Ken Lu's CC-API update slides for 2024/05/07

### PR DESCRIPTION
**Pull request by kenplusplus**
* Add files via upload
* Update README.md

### CODE REVIEW

**Comment by kenplusplus** [comment]
> hi @kenplusplus, quick question: is this slide deck intended to supersede the previous one?

It is OK to replace the previous one. @thomas-fossati  do you want keep the new record for 2024/05/07? or just replace the previous one?

**Comment by thomas-fossati** [comment]
> > hi @kenplusplus, quick question: is this slide deck intended to supersede the previous one?
> 
> It is OK to replace the previous one.

cool

> @thomas-fossati do you want keep the new record for 2024/05/07? or just replace the previous one?

I would coalesce the two, with "2024-04-23, 2024-05-07" in the date column.

**Comment by kenplusplus** [comment]
> > > hi @kenplusplus, quick question: is this slide deck intended to supersede the previous one?
> > 
> > 
> > It is OK to replace the previous one.
> 
> cool
> 
> > @thomas-fossati do you want keep the new record for 2024/05/07? or just replace the previous one?
> 
> I would coalesce the two, with "2024-04-23, 2024-05-07" in the date column.

Update at https://github.com/CCC-Attestation/meetings/pull/36/commits/3ebad170271fd489dad49b1454e17505348ab458 could you please review again?

**Comment by thomas-fossati** [comment]
Thanks @kenplusplus !  Question: is slide 4 superfluous now?  Or you want to keep it?

**Comment by kenplusplus** [comment]
> Thanks @kenplusplus ! Question: is slide 4 superfluous now? Or do you want to keep it?

Good reminder, in latest update at https://github.com/CCC-Attestation/meetings/pull/36/commits/4f01cf90c300a42b91b6e1673951c19645aca93e, I have removed slide 4, and move the page 1,2 to the end. Could you please help to review again? Thanks for your time.

**Review by thomas-fossati — APPROVED** [review]
awesome, thanks!

**Comment by kenplusplus** [comment]
@KeithMoyer Do you have additional guides and comments? Could you please help to merge?

**Comment by kenplusplus** [comment]
@gkostal Could you please help to merge? Thanks!

**Pull request merged**
